national_parks = [
    {
        "name": "Yellowstone National Park",
        "latLng": [44.4280, -110.5885],
        "description": "America's first national park, known for its geothermal features like Old Faithful.",
        "icon": "🌋",
    },
    {
        "name": "Yosemite National Park",
        "latLng": [37.8651, -119.5383],
        "description": "Famous for its giant, ancient sequoias, and the towering Bridalveil Fall.",
        "icon": "🌲",
    },
    {
        "name": "Grand Canyon National Park",
        "latLng": [36.1069, -112.1129],
        "description": "Iconic national park featuring a massive canyon carved by the Colorado River.",
        "icon": "🏜️",
    },
    {
        "name": "Zion National Park",
        "latLng": [37.2982, -113.0263],
        "description": "Known for Zion Canyon's steep red cliffs and scenic hiking trails.",
        "icon": "🏞️",
    },
    {
        "name": "Rocky Mountain National Park",
        "latLng": [40.3428, -105.6836],
        "description": "Home to spectacular mountain environments, including Longs Peak and Trail Ridge Road.",
        "icon": "🏔️",
    },
    {
        "name": "Glacier National Park",
        "latLng": [48.7596, -113.7870],
        "description": "Features rugged mountains, pristine forests, and alpine meadows.",
        "icon": "❄️",
    },
    {
        "name": "Great Smoky Mountains National Park",
        "latLng": [35.6118, -83.4895],
        "description": "Renowned for its biodiversity, misty mountains, and lush forests.",
        "icon": "🌫️",
    },
    {
        "name": "Grand Teton National Park",
        "latLng": [43.7904, -110.6818],
        "description": "Famous for its stunning mountain scenery and diverse wildlife.",
        "icon": "🏔️",
    },
    {
        "name": "Olympic National Park",
        "latLng": [47.8021, -123.6044],
        "description": "Diverse ecosystems ranging from Pacific coastline to alpine peaks.",
        "icon": "🏞️",
    },
    {
        "name": "Acadia National Park",
        "latLng": [44.3386, -68.2733],
        "description": "Known for its rocky beaches, woodland, and the tallest mountain on the U.S. East Coast.",
        "icon": "🏞️",
    },
    {
        "name": "Joshua Tree National Park",
        "latLng": [33.8734, -115.9010],
        "description": "Unique desert landscapes with Joshua trees and rugged rock formations.",
        "icon": "🌵",
    },
    {
        "name": "Arches National Park",
        "latLng": [38.7331, -109.5925],
        "description": "Home to more than 2,000 natural stone arches and stunning red rock formations.",
        "icon": "🪨",
    },
    {
        "name": "Bryce Canyon National Park",
        "latLng": [37.5930, -112.1871],
        "description": "Known for its unique geologic formations called hoodoos.",
        "icon": "🏞️",
    },
    {
        "name": "Shenandoah National Park",
        "latLng": [38.2928, -78.6796],
        "description": "Features the scenic Skyline Drive and part of the Appalachian Trail.",
        "icon": "🌄",
    },
    {
        "name": "Everglades National Park",
        "latLng": [25.2866, -80.8987],
        "description": "Largest subtropical wilderness in the U.S., famous for its wildlife and sawgrass marshes.",
        "icon": "🌿",
    },
]
